### PR TITLE
feat: reset modal body in ajax form

### PR DESCRIPTION
**Pull request by shadowgate15**
This will add the ability to reset modal-body using an ajax form.

### CODE REVIEW

**Comment by niftylettuce** [comment]
So this would be resetting the contents of the modal with the response message?

**Comment by shadowgate15** [comment]
yep. 

sorry about the review request. didn't see the comment...

**Comment by niftylettuce** [comment]
I think a better name might be `renderModalWithHTML` or something, not sure yet.  Reset sounds weird.

**Comment by shadowgate15** [comment]
Whatever you want, that isn’t a hard change to make.

**Comment by niftylettuce** [comment]
Can we make it so if `html` is specified in the response, then it simply renders a modal with that as its contents?  Could also pass an optional `title` which would be used for `modal-title` header.  Open to your thoughts, but that was kind of what I was thinking.

**Comment by niftylettuce** [comment]
I think though this might already be possible by using `swal` (SweetAlert2).  I think you can do `ctx.body = { swal: { ... } }` where `swal` is an object of options, which you could include HTML in.  Though that forces you to use SweetAlert2, which I think we're going to steer away from and on my wishlist is to use native bootstrap toasts instead and completely remove SweetAlert2.

**Comment by niftylettuce** [comment]
Did you still want this @shadowgate15 or should we drop?

**Comment by shadowgate15** [comment]
I would like it.

**Pull request merged**
